[2022-05-22 01:13:10,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-05-21T23:30:00+00:00 [queued]>
[2022-05-22 01:13:11,017] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-05-21T23:30:00+00:00 [queued]>
[2022-05-22 01:13:11,018] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 01:13:11,018] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-22 01:13:11,018] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-22 01:13:11,031] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_in_xlsx> on 2022-05-21 23:30:00+00:00
[2022-05-22 01:13:11,036] {standard_task_runner.py:52} INFO - Started process 307 to run task
[2022-05-22 01:13:11,038] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'convert_xls_in_xlsx', 'scheduled__2022-05-21T23:30:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp0eamicfb', '--error-file', '/tmp/tmpk_k2nnqd']
[2022-05-22 01:13:11,039] {standard_task_runner.py:80} INFO - Job 19: Subtask convert_xls_in_xlsx
[2022-05-22 01:13:11,083] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.convert_xls_in_xlsx scheduled__2022-05-21T23:30:00+00:00 [running]> on host 0a31d31582dc
[2022-05-22 01:13:11,148] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_in_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-05-21T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-21T23:30:00+00:00
[2022-05-22 01:13:11,919] {python.py:173} INFO - Done. Returned value was: None
[2022-05-22 01:13:11,932] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=convert_xls_in_xlsx, execution_date=20220521T233000, start_date=20220522T011310, end_date=20220522T011311
[2022-05-22 01:13:11,973] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-22 01:13:12,015] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
