[2022-05-19 03:30:06,278] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.e_valida scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:06,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Teste_ETL_Raízen.e_valida scheduled__2022-05-19T02:30:00+00:00 [queued]>
[2022-05-19 03:30:06,292] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:06,292] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-19 03:30:06,293] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 03:30:06,313] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): e_valida> on 2022-05-19 02:30:00+00:00
[2022-05-19 03:30:06,346] {standard_task_runner.py:52} INFO - Started process 3645 to run task
[2022-05-19 03:30:06,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Teste_ETL_Raízen', 'e_valida', 'scheduled__2022-05-19T02:30:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpt2c4r7y_', '--error-file', '/tmp/tmps3v7n0bb']
[2022-05-19 03:30:06,354] {standard_task_runner.py:80} INFO - Job 12: Subtask e_valida
[2022-05-19 03:30:06,458] {task_command.py:369} INFO - Running <TaskInstance: Teste_ETL_Raízen.e_valida scheduled__2022-05-19T02:30:00+00:00 [running]> on host c8caf9da75ac
[2022-05-19 03:30:06,613] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Teste_ETL_Raízen
AIRFLOW_CTX_TASK_ID=e_valida
AIRFLOW_CTX_EXECUTION_DATE=2022-05-19T02:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-19T02:30:00+00:00
[2022-05-19 03:30:06,638] {python.py:173} INFO - Done. Returned value was: nvalido
[2022-05-19 03:30:06,639] {skipmixin.py:140} INFO - Following branch nvalido
[2022-05-19 03:30:06,640] {skipmixin.py:175} INFO - Skipping tasks ['valido']
[2022-05-19 03:30:06,724] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Teste_ETL_Raízen, task_id=e_valida, execution_date=20220519T023000, start_date=20220519T033006, end_date=20220519T033006
[2022-05-19 03:30:06,766] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-19 03:30:06,820] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
